### ISSUE TITLE
I'm getting Render Error: (0, _reactNativeSafeAreaContext.useSafeAreaFrame) is not a function

### ISSUE THREAD

**Issue by mohamedabkal** [tribefyhq/react-native-interactive-walkthrough#2]
Hey I'm getting this error when I try to run the app ⬇️ 

```
TypeError: (0, _reactNativeSafeAreaContext.useSafeAreaFrame) is not a function. (In '(0, _reactNativeSafeAreaContext.useSafeAreaFrame)()', '(0, _reactNativeSafeAreaContext.useSafeAreaFrame)' is undefined)
```

<img src="https://user-images.githubusercontent.com/43915733/173406739-bf049d03-f7df-4244-8202-69693726d977.png" width="270" >

```
const { isWalkthroughOn, isReady, start } = useWalkthroughStep({
    number: 1,
    OverlayComponent: WelcomeMessageOverlay,
    fullScreen: true,
});

useEffect(() => {
    start()
}, [])
```

```
const WelcomeMessageOverlay = ({ next }: IOverlayComponentProps) => {
    return (
      <View style={styles.fullScreenContents}>
        <Text style={styles.h1}>
          Let's take a quick tour!
        </Text>
      </View>
    )
};
```

**Comment by netomarchiori** [comment]
do you have the code for your app? the snippets they provide are pretty inconclusive. I'm trying to setup something so I have a working example.

**Comment by mohamedabkal** [comment]
> do you have the code for your app? the snippets they provide are pretty inconclusive. I'm trying to setup something so I have a working example.

@netomarchiori I'm using the same example snippets provided in documentation.

**Comment by mohamedabkal** [comment]
This issue if fixed after upgrading `react-native-safe-area-context` to ^3.3.2 (I had 0.7.3 before)

**Comment by mohamedabkal** [comment]
This issue if fixed after upgrading react-native-safe-area-context to ^3.3.2 (I had 0.7.3 before)
